### ISSUE TITLE
ADD class - ”residency information content entity“

### ISSUE THREAD

**Issue by zhanghansi** [ufbmi/OMRSE#101]
In last week's Moonshot meeting, we talk about adding a new class ”residency information content entity“ in OMRSE. This is used to represent an patients' residency information.

**Comment by dillerm** [comment]
Do you have a proposed definition for this?

**Comment by sjbost** [comment]
@zhanghansi please reply with a full new term request (NTR) including all 7 items in these instructions: https://docs.google.com/document/d/1puOUogRRHi9MoIhBuTnv28QhoRAbr8EQiuLooN9SXSQ/edit#. For an example of how to do this see here: https://github.com/biobanking/biobanking/issues/62. Please follow up with me or @dillerm if you have any questions.

**Comment by zhanghansi** [comment]
@dillerm  
Requested this new term to OMRSE as issue #101 with the following specifications:

1. editor preferred term: residency information content entity
2. alternative terms: none
3. textual definition: An information content entity that is about some residential facility that a person lives at.
4. definition source: Suggested by Mathew Diller
5. logical definition: subclass of 'information content entity'
6. example of usage: A person's living address, such as street, city, county, or state information.
7. term editor: Hansi Zhang

**Comment by mbrochhausen** [comment]
Hi,

thanks for Matt for his help. Here are a few things to think about:
1. When I visit Germany I typically live with my family. They have a
"living facility" (I guess, see 2.) and I am a person. So, based on the
definition my family's address in Germany is an instance residential
information content entity. Is that the intended extension of the term?
Another fun example is that a colleague of mine in Germany for a while
lived (illegally) in his office for half a year. He certainly did not give
is office address as residential information, since that would have given
him away. I think residence is something that some explicitly or implicitly
declares and it is not necessarily closely related to where they live (at
the moment).
2. Barry Smith says a definition is supposed to make things easier to
understand. I don't think "residential facility" is a highly understandable
notion. Maybe this refers to an Apollo-SV class and that that'll help, but
if not, we need to find a more intuitive word.
3. This might be my limited knowledge of the English lexicon, but is
"living address" a thing?

**Comment by dillerm** [comment]
I think your insight about residence being something that one declares is an important one since someone can have a temporary residence (e.g., the dorm room that a student lives in for x amount of semesters) that they wish to declare in order to receive mail, register to vote, etc., or a temporary address like the ones you gave examples of in (1) that you would not generally declare as your residence, either because you're only living there for a very short time or you aren't allowed to declare it as your residence. I take it one way to modify the definition to reflect this would be to say that this class is the output of a declaration process and that a better subclass for it would be 'socio-legal generically dependent continuant'. What is your take on this?

In response to (2), ['residential facility'](http://www.ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/OMRSE_00000191) is actually an OMRSE class.

In response to (3), I'm not sure that "living address" is a thing, but I know that "current address" is.

**Comment by mbrochhausen** [comment]
Matt, thanks for your thoughts. Note that d-acts as it is in Ontobee is
still the olde version. The new version has done away with SLGDCs. In the
new d-acts, declaring your residency is neither a deontic declaration nor a
standing declaration. I do think it is a social act. I am not claiming that
it is always perceived, but in order to have an effect it needs to be
perceived.

**Comment by hoganwr** [comment]
Yes, what the individual declares to be his/her residence is important, but
the history of people fleeing the state of New York to escape high taxes
proves that one's own declaration is not the only or final world on where
is your residence, at least for the purpose of taxation.

Judges in New York have found that if you declare residence in Florida, you
still are liable for taxes in New York if your actions tend to show
otherwise: how much time you spend there, which place is the one where you
keep your pets, etc.

**Comment by hoganwr** [comment]
OMRSE has a class 'residential facility' and a definition for it. Before
you criticize that definition for using 'housing unit', we have a class for
that, too.

**Comment by mbrochhausen** [comment]
That is true. I propose that is a second (maybe more legal process), which
is about government/administration recognition of residency. In the US that
seems basically important for taxation. In Germany whenever you move, you
have to go to the regional administration and declare your residency there.
I think that the person declaring is always the first step.
I wonder to which extent the government/administration recognizes the
declared residency is relevant to the clinical data, though.

Best,
Mathias

**Comment by mbrochhausen** [comment]
Thanks for clarifying.

**Comment by hoganwr** [comment]
That's a good point re: clinical data.  I am not aware of incentives for
either the individual or the health care organization to prevaricate or
even litigate over what is the individual's residence.

**Comment by CDowland** [comment]
Looking over this discussion, I wondered whether it might be helpful to have an object property representing the relationship between a person and that person’s residence, and to use that property in the definition of ‘residence information content entity’. After all, it is not just the person and the place that the ICE is about, but also the fact that the person is a resident of that place.

Using the current definition of ‘residence function,’ here is a rough draft of the idea:

**Label**: ‘resident of’ (alternative terms: ‘resides at’, ‘resides in’, ‘has residence’)
**Domain**:  ‘organism’
**Range**: ‘material entity’ and (‘bearer of’ some ‘residence function’)
**Textual definition**: a relation of _a_ to _b_ that holds if and only if _b_ bears a residence function that is realized by _b_’s protecting _a_ and _a_’s possessions from weather, and by _a_’s habitually sleeping in at least one site that is contained by _b_
(The above definition is largely based on the definition of ‘residence function’.)

This could have an inverse property, ‘residence of’, simply defined as the inverse of ‘resident of’.

If we create the object property ‘resident of’, then perhaps ‘residency information content entity’ could make use of ‘resident of’ in its definition. Something like the following might work:

**Residency information content entity:** 
**Textual definition:** An information content entity that is about some organism’s being a resident of some material entity.
**Equivalency axiom (logical definition):** 'information content entity' and ('is about' some (‘organism’ and (‘resident of’ some 'material entity')))

[Perhaps 'material entity' in the textual and logical definitions should be replaced with 'housing unit', but I'm not certain.]

Potential setback: As pointed out in previous comments, the residency ICE might not correspond to the person's actual place of residence. But if you go with the idea of saying the ICE is about a person's declaring something about that person's residence, then perhaps 'resident of' would still be useful, as the declaration would be a (possibly false) claim that the person bears the 'resident of' relation to some place.

**Comment by mbrochhausen** [comment]
This is certainly a decision for OMRSE leadership. I personally always
discourage shifting the semantic weight from classes to object properties.
The formal ways to restrict object properties are, in my mind, way more
limited than the ones for classes. I think, right now our class might be
under-defined , but I think we could add additional representation step by
step that would in the end allow us to write a more restrictive subclassOf
or even equivalentClass axiom. With the object properties once we defined
domain and range we are pretty much done (as far as computer parsable
information goes).

Again, it is the decision of OMRSE leadership.

**Comment by sjbost** [comment]
@hoganwr @CDowland Do we have an update on this work? Just checking as I'm preparing the agenda for tomorrow's Moonshot Aim 2/4 meeting.

**Comment by CDowland** [comment]
@sjbost I'm not really in the loop on this one. I saw the discussion and commented with a possible approach that occurred to me, but that has been the extent of my involvement.

**Comment by sjbost** [comment]
@CDowland thanks for letting me know!

**Comment by dillerm** [comment]
Let's add it to the discussion for tomorrow's meeting

**Comment by dillerm** [comment]
One concern I have with using 'social act' in the definition is that there is no longer a class for this or at least the IRI does not resolve: http://purl.obolibrary.org/obo/IAO_0021003.

**Comment by CDowland** [comment]
The term still exists. The reason the PURL does not resolve is because it is a d-acts terms have IAO PURLS/IRIs. If you search it on Ontobee, the main PURL that shows up does not resolve, but by clicking the ones where it appears in other ontologies, such as its home ontology (d-acts), you can see it: http://www.ontobee.org/ontology/d-acts?iri=http://purl.obolibrary.org/obo/IAO_0021003

This happens in other cases, too. For example, 'deontic role':
This one does not work: http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0021008
But this one does: http://www.ontobee.org/ontology/d-acts?iri=http://purl.obolibrary.org/obo/IAO_0021008

**Comment by dillerm** [comment]
The term does not exist in the source ontology it was created in; therefore, I would argue that the term does not exist and should not at the moment be reused.

**Comment by CDowland** [comment]
That is incorrect. It is d-acts class, and still exists in d-acts. Just open d-acts in Protege and you'll see it. The same thing that's happening with this term will happen with every d-acts term, as well as PNO terms, since they all have IAO IRIs. Go to Ontobee and look up 'deontic role' (another d-acts class) or 'grapheme' (a PNO class) and you see similar results.

**Comment by dillerm** [comment]
I understand that d-acts imports this IAO class, but the class itself does not exist in IAO and as long as it has an IAO IRI, I would consider it a deprecated/deleted IAO class. Part of the purpose of sharing and reusing terms between ontologies is to avoid orthogonality and promote integration. Ignoring the fact that a term has been deprecated or altogether removed from an ontology when you decide to reuse it is not conducive to this goal.

**Comment by CDowland** [comment]
No, d-acts does not import it. D-acts is its home ontology. All d-acts classes have IAO IRIs. So do all PNO classes. That causes the issue with the PURLs resolving.

**Comment by dillerm** [comment]
Oh, wow, that's annoying and counterintuitive.

**Comment by CDowland** [comment]
Yes, it is a weird situation and confusing when first encountered. Hopefully it will be remedied somehow.

**Comment by hoganwr** [comment]
We've discussed this issue at length before.  A solution is the works.
Until then, it's just something to be aware of and to manage.

**Comment by CDowland** [comment]
I think that was mostly in some of our weekly PI/postdoc meetings, so Matt may not have been around for those discussions. It also came up briefly in relation to handling the language module, but only to the extent that we wanted to avoid this issue arising with it.

**Comment by dillerm** [comment]
To make up for my shenanigans, here are some of my thoughts on this issue of legal residence vs. residence declared in a clinical setting:

1. It is plausible that a person might declare in a clinical setting their local address as their place of residence even if it differs from their legal residence. For example, UF students who are not from Gainesville might share their local Gainesville address with UF Health instead of their legal residence. This is probably especially true for international students, although I may be mistaken. I also wouldn't be surprised if "snowbirds" (i.e., elderly people from the northern US who stay in the southern US for the Fall and Winter) give their physicians/hospitals in Florida their local address instead of their legal one.

2. The legal definition of 'residence' differs between countries and even between territories/states within those countries. Therefore, defining this class according to a precise legal definition is likely impossible. 

3. Therefore, I think whatever definition we propose (a) needs to be the specified output of a social act and (b) should not limit the class to being about one's legal residence. I actually think that the previous proposal that defines 'residency ICE' as "being about some residential facility that a person lives at" is broad enough to capture everything we need in part (b) since it covers both permanent and temporary residences. Now if we're really concerned with the possibility of patients providing addresses to non-residential facilities (e.g., their office), we can further broaden the definition by changing 'residential facility' to 'facility'. 

Here is the new proposal: "An information content entity that is about some residential facility that a person lives at and is the specified output of a social act."

Is there anything more that this definition needs to capture?

**Comment by hoganwr** [comment]
Matt, all,

I agree with the reasoning here.  I am fine with this definition.  I don't
think there's anything else it needs to capture, but I am not familiar with
the data source here.  This is for Hansi' work on some cancer data sources,
right?

Bill

**Comment by CDowland** [comment]
A minor suggestion: perhaps replace 'residential facility' with 'housing unit.' Two reasons for this:

1. If I understand correctly, the apartment building I live in is a residential facility, but my residency ICE would be about the specific apartment (a housing unit) in which I live. I take it a one-family house would count as both a residential facility and a housing unit.

2. Furthermore, the definition for 'housing unit' says it bears a residence function, while the definition for 'residential facility' does not. It is by having some housing unit(s) as part(s) that a residential facility connects to some residency function(s).

**Comment by hoganwr** [comment]
I tend to agree with Clint, but again it spends on the source data and how
they describe and use the data item.

**Comment by mbrochhausen** [comment]
Very nice!

**Comment by sjbost** [comment]
@hoganwr Yes, this is for @zhanghansi Moonshot work related to tumor/cancer representation. I don't remember what, specifically, Hansi is modeling that requires this term.

**Comment by dillerm** [comment]
@zhanghansi, can you provide a description of the data item this is for?

**Comment by zhanghansi** [comment]
> @zhanghansi, can you provide a description of the data item this is for?

The data item that I have in FCDS related to patient residency information is the zip code.

**Comment by dillerm** [comment]
Is it a 3-digit, 5-digit, or Zip+4 code?

**Comment by sjbost** [comment]
According to @zhanghansi , the source data contains 5- and 9-digit ZIPs.
