### ISSUE TITLE
OMRSE_00000033 aggregate of organizations has two definitions

### ISSUE THREAD

**Issue by zhengj2007** [ufbmi/OMRSE#174]
OMRSE_00000033 aggregate of organizations has two definitions
- An aggregate of organizations that have some feature in common, but is not itself an organization.
- An object aggregate that is not itself an organization and whose members are only organizations that have some feature in common

Should remove one.

Besides, the term has 'imported from' annotation: http://purl.obolibrary.org/obo/omrse.owl. I think it should be deleted.

**Comment by CDowland** [comment]
Thanks for calling this to our attention. This appears to be a previously resolved problem that is now returning. 

Source of the issue: D-acts has individually imported some OMRSE terms, including some that have been revised since the time they were imported. And since OMRSE now imports all of d-acts, OMRSE is getting back its old versions of those terms.

This was addressed and fixed before: https://github.com/d-acts/d-acts/issues/32.

But I see the latest version of d-acts somehow has the old versions of those terms again. So we may be once again getting our old version back from d-acts, and then it is combined with the current one as one term. But I don't think that's happening with the other terms that are also once again appearing as their old version in d-acts, so I'm a bit confused. I will ask about it over on the d-acts issue tracker: https://github.com/d-acts/d-acts/issues/32.

**Comment by wdduncan** [comment]
I **seem** to recall (and I may be completely wrong) that you can edit the appropriate `*terms.txt` file (e.g. `d-acts_terms.txt`) in order to specify which terms are used when building the import file. Here is a link to the "update import" instructions for `pato`:
http://pato-ontology.github.io/pato/odk-workflows/UpdateImports/   

I will try to read later.

Also, duplicate definitions exist elsewhere in the `omrse-edit.owl` file. E.g. see screenshot for `continuant`.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/3186638/171459218-1a0655da-e608-40cc-9610-8c46c0ba4a58.png">

**Note**: In the latest `omrse.owl` release (i.e., `http://purl.obolibrary.org/obo/omrse/releases/2022-04-06/omrse.owl`), the duplicate definitions for `continuant` do not exist  However, there are still two (distinct) definitions for `aggregate of organizations`. 

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/3186638/171460360-3667a647-a1c6-432a-a002-fb80c3c295b1.png">


This makes me wonder if duplicates are removed as part of the ODK process to create a release (I can't recall).
