### ISSUE TITLE
Create Age Measurement Datum

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#19]

**Comment by dwelch2101** [comment]
Initial Proposed Definition:
A time measurement datum that is the result of measuring the duration of a temporal region onto which part or all of a history projects, typically beginning with the left process boundary of the history and ending with the time that the measurement was made.

Current weakness: it counts a measurement of the middle 20 years of some 80 year-old person’s life as an age.  

Cannot restrict beginning of interval to left boundary of history because that excludes age since birth.  Saying that it’s the time the entity has instantiated a particular universal works only if we count human beings at/after time of birth but not fetus before.  

Axiom:
‘time measurement datum’ and (‘is about’ some (‘one dimensional temporal region’ and (‘is occupied by’ some (‘is part of’ some history)))) and (‘has measurement unit label’ only ‘time unit’)

**Comment by aellenhicks** [comment]
Class created URI: OMRSE_00000080
