### ISSUE TITLE
NTR: U.S. veteran role

### ISSUE THREAD

**Issue by CDowland** [ufbmi/OMRSE#205]
**Preferred term label:**  
U.S. veteran role 

**Textual definition:**  
Deontic role that inheres in a person if and only if that person (i) served in the active military, naval, or air service of the United States, and who was discharged or released therefrom under conditions other than dishonorable, or (ii) is a Reservist or member of the United States National Guard called to Federal active duty or disabled from a disease or injury incurred or aggravated in line of duty or while in training status; and that is realized by processes in which that person participates, where participation is allowed in virtue of the person’s meeting condition (i) or (ii). 

**Definition source:**  
38 U.S.C. §101(2), as well as “Determining Veteran Status” by the U.S. Department of Veterans Affairs (VA) Office of Small and Disadvantaged Business Utilization (OSDBU): https://www.va.gov/OSDBU/docs/Determining-Veteran-Status.pdf. 

**Suggested parent term:**  
deontic role

_Why OMRSE:_

While veteran status is determined by events that occurred in that person's past, there is something ongoing that is referred to when we talk about someone being a veteran, and it socially determined to an extent. This is reflected in the fact that there is a legal definition of "veteran" in the United States, and that those who meet the requirements laid out by that definition are allowed access to certain programs/resources they otherwise would not be. There is an additional sense in which it is socially determined, since whether someone has veteran status is (or can be) contingent upon whether the person was honorably discharged.

It is medically relevant because it affects the type of health care options and assistance available to the person. Furthermore, some consider military experience to be a social determinant of health; and in some data sets the only indicator of whether a person has military experience is a data element about whether the person is a veteran.

**Comment by dillerm** [comment]
Proposed revision with reasons below: "Deontic role that inheres in a person if that person (i) served in the active military service of the United States, and who was discharged or released therefrom under conditions other than dishonorable, or (ii) is a Reservist or member of the United States National Guard called to Federal active duty or disabled from a disease or injury incurred or aggravated in line of duty or while in training status."

**Proposed Changes:**

1. Shorten "if and only if" to "if" since we cannot axiomatize it in a way that perfectly captures the necessary and sufficient conditions that are outlined in the definition. 
2. Shorten "military, naval, or air service" to "military service" since the use of 'naval' and 'air' is redundant.
3. Remove the last part of the definition--"and that is realized by processes in which that person participates, where participation is allowed in virtue of the person’s meeting condition (i) or (ii)"--since the processes that can realize this role are so vast and dissimilar that this text doesn't add much information to the definition. For instance, someone can realize a US veteran role to receive a discount at a movie theater, to receive medical care at a VA hospital, or to claim membership with a Veterans of Foreign Wars (VFW) Post.

**Comment by wdduncan** [comment]
> Shorten "if and only if" to "if" since we cannot axiomatize it in a way that perfectly captures the necessary and sufficient conditions that are outlined in the definition.

FWIW, I think the definition reads fine w/o "if". I.e., "A deontic role that inheres in a person who/that (1) served ...."   

The canonical form of a genus-differentia definitions is `A is B that Cs`. This doesn't require the use of "if", "only if", "if only if" etc. These phrases play important roles when wanting to express the definition in FOL, but not so much in Aristotelian systems (i.e., syllogisms).

> Deontic role that inheres in a person if and only if that person ...

I'm not sure that `deontic role` is the best parent. `Deontic role` is defined as:
```
A role that inheres in an agent and which is externally grounded in the normative expectations that other agents within a social context have concerning how that agent should behave.
```
As a veteran myself I am not aware of any "normative expectations" that have been placed on me in this regard.  

A better parent may be `human social role`. It is descended from `role in human social process`, which is defined as:
```
A role inhering in an entity realized by social interactions in human society.
```
IMHO, this better captures that a person's status as a veteran rests on the interactions with society, and not on obligations that a veteran is obligated to fulfill.

**Comment by CDowland** [comment]
@wdduncan 
I see what you’re saying about how being a veteran does not entail any particular obligations are expected of someone, and the same concern made me hesitate a bit when deciding on a parent class to propose. Here’s why I nonetheless suggested ‘deontic role’:

Whether or not someone bears a veteran role makes a difference to “the normative expectations that other agents within a social context have concerning how that agent should behave.”

For example we have the normative expectation that non-veterans will not attempt to access health care services that are intended only for veterans, but that is not the case for veterans. 

But you’re correct that it is realized by processes that count as social interactions, so your suggestion to use ‘role in human social processes’ as the parent also makes sense. Presumably there’s a great deal of overlap between deontic roles and human social roles. I think either works here.

**Comment by wdduncan** [comment]
> Presumably there’s a great deal of overlap between deontic roles and human social roles. I think either works here.

Yes, there very well maybe a great deal of overlap :)  FWIW, I still think `role in human social process` makes better sense.

**Comment by dillerm** [comment]
I'm leaning more in favor of `deontic role` because there is a claim associated with the role w.r.t. access to VA healthcare. In this case, normative expectations are that VA doctors and nurses will provide healthcare to anyone who is classified by the VA as being a veteran. However, it's my understanding that the d-acts classes that represent claims, privileges, etc. (all of which are subclasses of `deontic role`) are based on the Hohfeldian Analytical System, and there are a number of "courtesies" that folks outside the VA system grant to veterans--access to membership with local VFW or DAV groups (for qualified veterans) or discounts at various businesses--that may not be Hohfeldian claims due to not being accompanied by a duty. For instance, access to a veterans' discount at a movie theater can be denied to a veteran by theater personnel without recourse because the movie theater's discount is not in any way binding. At the moment, I don't think this is problematic for @CDowland 's proposal to classify this class as a `deontic role`, but it might motivate consideration for additional deontic roles in d-acts.

**Comment by wdduncan** [comment]
@dillerm It sounds to me like you describing obligations (i.e., deontic roles) that the doctor's, nurses, and other VA personal (and government organizations) have concerning how they are supposed to care for veterans. I agree that seeking care at the VA would realize a patient's veteran's `U.S. veteran role`, but I don't see how or why the veteran is obligated to seek such care.  
Perhaps we understanding 'deontic' differently?

**Comment by dillerm** [comment]
Yes, I think you are thinking of the more conventional definition of 'deontic' whereas I am using d-acts' definition for [`deontic role`](https://ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/IAO_0021008). The veteran isn't obligated to seek out care at a VA health facility, but they do have a claim to those services by virtue of bearing such a role. In d-acts, [`claimant role`](https://ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/IAO_0021013) is used to represent a claim and, like Hohfeldian claims, necessarily has a corresponding duty, represented by [`duty holder role`](https://ontobee.org/ontology/OMRSE?iri=http://purl.obolibrary.org/obo/IAO_0021016). Both of these classes are subclasses of `deontic role`.

**Comment by mbrochhausen** [comment]
I think this is an institutional role, that comes with deontic roles.
Remember that part of how d-acts works now is that there multiple levels of
roles.

Just my 2 cents. Happy to get on a call about it.

Best,
Mathias

**Comment by wdduncan** [comment]
The definition from `d-acts` for `deontic role` reads:

> A role that inheres in an agent and which is externally grounded in the normative expectations that other agents within a social context have concerning how that agent should behave.

Perhaps I'm being a fuddy duddy and being overly focused on the part of the definition that says "how that agent should behave".  Again, I am not aware of any such normative expectations of behaviors for U.S. veterans. To me, at least, this akin to saying that retired firemen or retired teachers have normative expectations on how they are supposed to behave.

I'm not familiar with Hohfeldian claims. From I found on the internet, they look very legalistic in nature.

So, how do we break out of this back and forth? Perhaps you can redefine `deontic role` so that it represents a broader set of expectations/behaviors? 

Happy to have a call :) We can arrange over email if you wish.

**Comment by mbrochhausen** [comment]
Sorry, I probably should have stayed out of this debate. I am not sure I
understand what your opinion is, Bill. I thought you were saying that
U.S. veteran is not a deontic role? If so, I wholeheartedly agree. It is an
institutional role that comes with deontic roles.

**Comment by wdduncan** [comment]
> Sorry, I probably should have stayed out of this debate.

Hah! I am delighted to have your input! :)

> Bill. I thought you were saying that U.S. veteran is not a deontic role? If so, I wholeheartedly agree.

Yes, we agree. I was saying that I think `U.S. veteran` is not a `deontic role`. Sorry, if I did not communicate this better.  

My comment was in response to the @CDowland and @dillerm who I think are arguing that it should be a type of `deontic role`. The justification being that it is akin to `claimant role`. I can see how a veteran could have a `claimant role` if they were filing a claim against the Veterans Administration (or similar organization). But, I don't think such a possibility necessarily entails that `U.S. Veteran role` is a type of `deontic role`,  unless (of course) you redefine things.

BTW, I couldn't find `institutional role`. Is it defined somewhere?

**Comment by mbrochhausen** [comment]
I think institutional role has been defined in a slide deck by Neil Otte. I
can probably dig that up. I should probably go into OMRSE.

**Comment by CDowland** [comment]
Claimant roles don't require "filing a claim." The definition:

`A deontic role that inheres in an agent A, that mutually depends on the existence of a duty holder role borne by agent B, and that specifies B doing or abstaining from C, or providing or surrendering C to A. `

For example, if the local movie theater offers discounts to veterans, then an employee (B) is required to give the discount (C) to a veteran (A). 

In any case, the fact that claimant roles are deontic roles would seem to undermine the concern about whether deontic roles must entail obligations of the bearer.

**Comment by wdduncan** [comment]
> Claimant roles don't require "filing a claim." 

Good point. I was trying to provide some context about when a veteran would become a claimant. 

> For example, if the local movie theater offers discounts to veterans, then an employee (B) is required to give the discount (C) to a veteran (A).

This is an obligation the theater takes on and (from what I understand of `claimant role`) bestows a `claimant role` on a person in virtue of them being a veteran. But, this doesn't entail that a veteran is obligated to go visit the theater. 

Being a veteran (i.e., bearing a `U.S. veteran role`) does not necessarily require that there exists any organizations that are obligated to provide services to them. In other words, all `claimant roles` that are created for veterans could cease to exist, and still someone could be a veteran.

**Comment by CDowland** [comment]
> Being a veteran (i.e., bearing a `U.S. veteran role`) does not necessarily require that there exists any organizations that are obligated to provide services to them. In other words, all `claimant roles` that are created for veterans could cease to exist, and still someone could be a veteran.

Interesting. The existence of such claims and associated processes are what led me to think of veteran status as role. If we distinguish those claimant roles from the veteran role, then what processes could realize the veteran role?

**Comment by hoganwr** [comment]
I seriously doubt this stuff is going away anytime soon.
[image: Screenshot 2023-04-25 at 7.20.49 PM.png]

**Comment by wdduncan** [comment]
>  If we distinguish those claimant roles from the veteran role, then what processes could realize the veteran role?

Thanking a veteran for their service.

**Comment by mbrochhausen** [comment]
So, here are some thoughts:

Veteran's claims are heterogenous in their origin and in who the duty holder is. The these as examples:

Veteran Jane Doe's claim to a free lunch at Bernie's Burger Shack on Veterans Day

Veteran John Doe's claim to aa reduced ticket at the Waning Light Arkansas State Park.

Veterans Jane and John Doe's claim to receive treatment at a VA medical provider.

All these are separate claims. They are not the veteran role, but they are linked to it.

So, how does on realize a veteran role.

Some things that might have not been aware of that underlies Neil's and my treatment of these role:

One action can realize more than 1 role!

Here is the draft definition of institutional role: "
"the role within an organization for which one was primarily hired." Obviously, that definition currently does not cover veterans, but I think it should. As it should cover professor emeritus. So, in implementing institutional role we need to take that into consideration.

Now, let's think about realizing institutional roles. My institutional role at UAMS is professor. Associated with that institutional role is a deontic role that obliges me to teach at a level of 10% of my time in the DBMI programs. If a student from another program comes to me and asks to learn method x, I will probably set up time to teach that student. This will not realize my duty holder role to teach in our program. But it realizes my institutional role as professor.
Veterans and professor emeriti are different, since they are out of active duty in their fields. They still hold claims and enjoy privileges that are attached to their institutional roles. Notably, in order to be eligible for those role they both had to be actively involved in their institutions respective mission.

I don't know a lot about veterans outside the VA health aspect. But I assume that veterans can apply and maybe reapply for a badge or card or pass that verifies their status as a veteran, this application would be an example of the veteran role being realized.

Let me know whether that makes sense.

**Comment by wdduncan** [comment]
Thanks @mbrochhausen !

> One action can realize more than 1 role!  

Right!

I like the "institutional" approach.  
Question: What would be the parent of `institutional role`?

**Comment by CDowland** [comment]
@mbrochhausen Great explanation. I found the example at the end particularly helpful, as it shows why it should be considered a role even while distinguished from the associated claimant roles. (I guess there may also be a claimant role there as well, as the bearer has a claim to the card; but in the other examples the card would be needed to verify the role, while the role is the prerequisite for the process of obtaining the card). Thanks!

**Comment by dillerm** [comment]
So should we implement `institutional role` in OMRSE? I know @mbrochhausen has already suggested doing so. I don't have any objections to the proposed definition for it.

**Comment by mbrochhausen** [comment]
That would be awesome! But the definition needs some work....

Best,
Mathias

**Comment by CDowland** [comment]
> * Do we want to restrict to the discharge criteria specified by the VA definition? E.g., A census question may only ask if a person served in the military, but not ask about discharge status.

I think the restriction is necessary for properly conveying who bears that type of role. A dishonorably discharged person or a person still serving does not bear a U.S. veteran role, i.e. does not have veteran status according to the legal definition. 

There is of course a sense of "veteran" that is simply meant to describe those who have served on active duty, and that's what something like the census question you mentioned is asking about. Your example highlights that representing military service itself could be of use as well. But serving on active duty is not sufficient for having veteran status by the legal definition. Instead of concerning a role one bears, it would instead be a matter of the person having a history that has a certain type of process as a part. So if for example the process was labeled 'serving in the military', then something like `'has history' some (BFO: history and 'has part' some 'serving in the military')` would be one possible way to represent it.

**Comment by wdduncan** [comment]
> There is of course a sense of "veteran" that is simply meant to describe those who have served on active duty, and that's what something like the census question you mentioned is asking about. Your example highlights that representing military service itself could be of use as well. But serving on active duty is not sufficient for having veteran status by the legal definition. 

IMHO, restricting the use of the term `U.S. veteran` to only those that satisfy the VA's criteria, seems overly restrictive (due to the use cases already noted). 
If the use case for this term is defining who receives health care from the VA, then it may better create a `VA health care patient role`. There are cases in which non-veterans receive health care at the VA.

**Comment by CDowland** [comment]
Part (i) of the definition is the criteria for being a veteran according to the U.S. code (38 U.S.C. §101(2)), with part (ii) being the addition that the VA's definition makes to part (i). It is in virtue of these that the type of role in question exists. Some roles are created by institutions or organizations having defined things in certain ways, and this is one of them. When defining such roles, we cannot ignore how the relevant institutions or organizations define them, or else we're defining something else. 

If by "the use cases already noted" you mean the census question you mentioned, then that does not ask about a role of any kind. It asks whether a person's history includes military service, and is the same (in a 'yes'/'no' sense) for a veteran, a person who was dishonorably discharged, or a person who still serves. Having a history that has a military service as a part is not the same thing as having veteran status in the legal sense. 

If the goal is representing the status defined in 38 U.S.C. §101(2), then a role is the way to go. 
If the goal is representing that a person has at some time served in the military, then military service can be represented as a type of process, and a person can be represented as having a history that has that sort of process as an occurrent part. But that's not a matter of bearing some type of role (and while being enrolled may entail bearing a certain type of role, it's a different role than that associated with veteran status defined in 38 U.S.C. §101(2)).

These goals are compatible. My request concerns the first, and you've given an example of data that warrants the second. But they concern different sorts of entities. One is role. The other is a process.

**Comment by wdduncan** [comment]
> Part (i) of the definition is the criteria for being a veteran according to the U.S. code (38 U.S.C. §101(2)) ...

Yes. I understand that there is a specific legal definition of 'veteran'. IMHO, it doesn't line up well with other contexts in which the word 'veteran' may be used. I guess we just disagree on this. So, others should weigh in order for us to reach a consensus.

> person can be represented as having a history that has that sort of process as an occurrent part.

Currently the `history` class in OMRSE does not have any children. So, this would be new territory. I'm not opposed to such development, but we need to think if we want OMRSE to include histories. If the driving use case is representing patients at the VA, then the more straightforward approach (I think) would be to create a `VA patient role`.

**Comment by hoganwr** [comment]
I’m in favor of Clint’s proposal and rationale. If we need to clarify it we
could add an editor preferred term that says something like US veteran
legal role.

We don’t need to subclass history to do what Clint suggested, we would need
to represent some “military activity” process and then for the sense of
ever having participated in such a process, say that that activity was a
part of the person’s history.

**Comment by wdduncan** [comment]
> I’m in favor of Clint’s proposal and rationale. If we need to clarify it we could add an editor preferred term that says something like US veteran legal role.

I'll go along with whatever the consensus is :)   
If this is what the final decision is, it might be worth modifying the definition so that it read less legalese. E.g., something like:
```
A human role within an organization that inheres in a person who has served in a 
branch of the U.S. military, is not currently serving in the U.S. military, and the 
person's service ended in accordance to conditions defined the U.S. government.
```
This definition allows for changes in the legal definition of 'veteran' w/o necessarily having to change the ontology definition.

> We don’t need to subclass history to do what Clint suggested, we would need to represent some “military activity” process and then for the sense of ever having participated in such a process, say that that activity was a part of the person’s history.

Good point!

**Comment by dillerm** [comment]
I like the idea of using @wdduncan 's definition here and adding a comment with the legal definition that @CDowland  included in his proposal.

**Comment by LightGrenadier** [comment]
We will use the following definition:
A human role within an organization that inheres in a person who has served in a 
branch of the U.S. military, is not currently serving in the U.S. military, and the 
person's service ended in accordance to conditions defined by the U.S. government.
