### ISSUE TITLE
term request: clinic

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#38]
proposed definition: A clinic (or outpatient clinic or ambulatory care clinic) is a health care facility that is primarily devoted to the care of outpatients.
Definition source: https://en.wikipedia.org/wiki/Clinic

**Comment by aellenhicks** [comment]
'outpatient clinic facility' exists.  OMRSE_00000110
A definition will be added shortly.

**Comment by mbrochhausen** [comment]
While I didn't see 'outpatient clinic facility', what we need is not facility (which is an architectural structure), but I need either a outpatient clinic role or an outpatient clinic as an organization. For our use cases the buildings/sites are not relevant. Thanks.

**Comment by aellenhicks** [comment]
Facilities are modeled as bearers of functions rather than roles.  Is 'outpatient facility function' is sufficient for your needs? If so, you might refer to OMRSE_00000120.  

Otherwise, we will model an appropriate role or organization.  We are currently working on ways modeling facilities in relation to roles and organizations.  See issue #32 and the wiki page on adding a typology of facilities.  If you have any suggestions, please add them to the wiki or issue #32.

**Comment by mbrochhausen** [comment]
Thanks. I am not sure that the function will work for our use case. I am fine with waiting for the appropriate role or organization being modeled in OMRSE. Until then can we please keep this issue open and close it once that is done?

**Comment by aellenhicks** [comment]
Hi Mathias,

Since there is already an issue that addresses this addition, I've closed
it as a duplicate, not as a completed task.

best,
Amanda

On Thu, Sep 17, 2015 at 12:36 PM, mbrochhausen <notifications@github.com>
wrote:

> Thanks. I am not sure that the function will work for our use case. I am
> fine with waiting for the appropriate role or organization being modeled in
> OMRSE. Until then can we please keep this issue open and close it once that
> is done?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ufbmi/OMRSE/issues/38#issuecomment-141142498>.
>



-- 
Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932 <%28352%29%20294-4197>
f: (352) 273-8703
aehicks@ufl.edu <hoganwr@ufl.edu>

**Comment by mbrochhausen** [comment]
Oh ok, I understand now. Thanks for clarifying,
Mathias
