### ISSUE TITLE
revise textual definition of hospital function

### ISSUE THREAD

**Issue by mbrochhausen** [ufbmi/OMRSE#40]
Currently, the definition reads: "A function inhering in a material entity that is realized by the material entity being the site at which inpatient and outpatient healthcare is provided to a patient population."
I think, it should be: "A function inhering in a material entity that, if realized, is realized by the material entity being the site at which inpatient and outpatient healthcare is provided to a patient population."
I overlooked this when I provided the definition, initially.

**Comment by mark-jensen** [comment]
How are you using 'site' here? In the BFO sense of [`site`](http://www.ontobee.org/ontology/BFO?iri=http://purl.obolibrary.org/obo/BFO_0000029)

If so, then this may be better expressed something like:
"... realized by the material entity that bounds the site at which ..."

**Comment by mbrochhausen** [comment]
Suggestion from Selja Seppälä:
"A function inhering in a health care facility that is realized by the health care facility at which inpatient and outpatient healthcare is provided to a patient population. »
OR
"A function inhering in a health care facility at which inpatient and outpatient healthcare is provided to a patient population."

**Comment by aellenhicks** [comment]
How is the following definition?

"A function inhering in a material entity that, if realized, is realized by the material entity being the bounds of a site at which inpatient and outpatient healthcare is provided to a patient population."

**Comment by mbrochhausen** [comment]
+1

**Comment by mark-jensen** [comment]
Some say "she's at the hospital". Others say "she's in hospital" (as "in hospice").

A concern I have after looking at this more closely is that you're giving the *function* of being a hospital to a building (essentially). You're saying the function is realized *when* inpatient and outpatient healthcare is provided in the site the building bounds.

Functions (as dispositions) are intrinsic to their bearers, existing via selection and design, and can only come and go with a corresponding material change in their bearers.

Say that, a building is constructed with the intention of being a hospital. After 5 years as a functioning hospital, the organization running the hospital is merged with some giant HMO and all the staff an equipment is moved to a fancy new building co-located with a shopping mall. The old building is no longer a hospital because it doesn't bound a site where inpatient and outpatient healthcare is provided. Has it lost its function?

Conversely, what if all the staff and equipment is moved into an abandoned school where they begin to provide inpatient and outpatient healthcare services? Has the building gained a hospital function? What about the *structure itself* has changed?

My thought is that we're talking about roles here. A building bears a `hospital role` (perhaps some kind of `facility role`) in virtue of it being the bounds of site where inpatient and outpatient healthcare is provided. There is an organizational and fiat aspect to it being a hospital, i.e., extrinsic to the structure itself. Hospitals have to get certified and formally approved. Or, at least some minimal social act probably happens that makes it the case.

`hospital role` = a role inhering in a material entity by virtue of the fact it bounds a site containing an aggregate of entities, which are capable of providing both inpatient and outpatient healthcare to a patient population.

As a postscript: I am increasingly of the mind that `system` can be helpful in cases like this. Contained within the site a hospital facility bounds is an aggregate of casually related entities (desks, computers, x-ray machines, beds, bedpans, and so on), all bearing various roles, dispositions, and so on. These combine as a system, which bears a disposition to provide inpatient and outpatient healthcare. The building is only part of that system.

**Comment by hoganwr** [comment]
We really are talking about a function.  The modern hospital is equipped
with far more than mobile units that enable it to serve as a hospital.
There are numerous things integral to the design and construction of the
facility.  Modern building codes specifically address hospitals:
http://www.csemag.com/single-article/healthy-hospital-success-codes-and-standards/676bd90290ddae53c43239e5847640a0.html

Yes, once no longer used as a hospital, depending on how much modification
is done, it would indeed still bear the function.  It would just not be
realized.

For a makeshift hospital where a building is used for the purpose that
wasn't designed for it, we agree.  The OMRSE class 'hospital facility' does
not apply.  We were not trying to make it do so.

**Comment by aellenhicks** [comment]
I have changed the definition to "A function inhering in a material entity that, if realized, is realized by the material entity being the bounds of a site at which inpatient and outpatient healthcare is provided to a patient population."

Are there any objections to closing this thread?

**Comment by hoganwr** [comment]
None from me :-)
