### ISSUE TITLE
Definition request - 'employee role'

### ISSUE THREAD

**Issue by dillerm** [ufbmi/OMRSE#44]
I'd like to use OMRSE's 'employee role' in Apollo-SV, however the class currently is undefined. As such, I'd like to propose the following definition for it:

"A human role within an organization that is realized when the bearer participates in some process of employment and in which the organization is the bearer of some employer role."

**Comment by aellenhicks** [comment]
Perhaps we can try to define what it means to participate in a process of employment in order to avoid circularity or a vague definition. Here are some initial thoughts.

Money or remuneration of some kind is involved, i.e., the employee is paid by the employer. This is in exchange for services, and as such involves a plan specification.

How about "A human role within an organization that is realized when the bearer provides labour or services in exchange for a wage or salary and in which the employer is the bearer of an employer role."

Or we can create a class for employment process and define it along the following lines.

"A planned process in which an the bearer of an employer role provides wages or salary to the bearer of an employee roll in fullfillment of some contract."

**Comment by mark-jensen** [comment]
This is essentially the same way we define it in [SDGIO](https://github.com/SDG-InterfaceOntology/sdgio), adapted somewhat from [eagle-i](http://purl.obolibrary.org/obo/ERO_0000787).
I didn't like their use of 'occupation' or 'earns living'.

We define `employee role`=
A role that inheres in a person and is realized by performing actions specified by an employer in return for remuneration.

`employment process` = 
A planned process wherein an employee performs actions that are specified by an employer in return of remuneration.

We don't specify the organization or contractual side because in some contexts, people are employed informally, or by individuals, or self-employed, possibly without the standard protections and agreements that come from formal employment contracts. 

It would be good to coordinate. No need to have two (or more) ontologies with functionally identical classes, but different IRIs. Pretty sure we would be ok with importing from OMRSE, but we need to allow for informal employment as well. Although, this class is more general than the medical domain. Are there plans for extracting "up" some entities into a generic social ontology? Know anybody working on that ;-)

**Comment by aellenhicks** [comment]
"We don't specify the organization or contractual side because in some contexts, people are employed informally, or by individuals, or self-employed, possibly without the standard protections and agreements that come from formal employment contracts."

I definitely see the need for a non-contractual form. For example, we needed this class for epidemic modeling. It is certainly the case that a person need not have a contract with an employer in order to spread disease in a workplace. We can certainly make it neutral with respect to that. 

Yes, let's coordinate! I like your definitions. I'm ok with housing them in either ontology.

There are no plans on our side to abstract up a level. TBH I have been playing the logic card and telling myself that "medically related" doesn't mean "non-medically unrelated", which is just to say, I see your point, but I'm not sure how much of a problem it is. I go back and forth.

**Comment by dillerm** [comment]
Agreed; I like those definitions, as well!

**Comment by aellenhicks** [comment]
Mark, what are next steps on coordinating with this?

**Comment by aellenhicks** [comment]
@mark-jensen, are you still interested in coordinating with this?

**Comment by aellenhicks** [comment]
a role in human social processes that is realized when the bearer provides labour or services in exchange for a wage or salary as specified by some declaration

**Comment by aellenhicks** [comment]
Is now a subclass of "role in human social process" with the following definition.

a role in human social processes that is realized when the bearer provides labour or services in exchange for a wage or salary as specified by some declaration
