### ISSUE TITLE
add housing unit and household

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/OMRSE#5]
See Wiki page on it.

**Comment by aellenhicks** [comment]
Proposed textual definition - "A material entity that has as parts one or more sites large enough to contain humans, has as part one or more material entities that separates it from other sites, and bears a residence function.  The residence functions also individuate the housing units."

**Comment by aellenhicks** [comment]
Are pets members of households?

**Comment by hoganwr** [comment]
For sure the U.S. census doesn't count them.

We could have a household class that includes them and a U.S. Census
household class that does not.

But in general I think pets are not included.

Bill

**Comment by aellenhicks** [comment]
'housing unit' is complete - OMRSE_00000074

'household' has been added - OMRSE_00000076 - Still needs a definition and class restriction.

**Comment by aellenhicks** [comment]
In light of the following definitions I propose the a definition of 'household' below.

Residence function -  The function of a material entity to protect persons and their possessions from weather and for one ore more of its sites to be the place where humans sleep.

Housing unit -  A material entity that has as parts one or more sites large enough to contain humans, has as part one or more material entities that separates it from other sites, and bears a residence function.

Proposed definition 
Household - A collection of humans that occupies a housing unit by storing their possessions there and habitually sleeping there thereby participating in the realization of its residence function.

**Comment by hoganwr** [comment]
I agree with the proposed definition of 'household'.

**Comment by aellenhicks** [comment]
Sorry, Bill.  I just modified it after looking up the definition of 'object aggregate'.
Here's the new one.

Proposed definition
Household - A human or collection of humans that occupies a housing unit by storing their possessions there and habitually sleeping there thereby participating in the realization of its residence function.

Note: A household can not be a subclass of 'object aggregate' since object aggregates possess non-connected boundaries and households can have one person in them.
