### ISSUE TITLE
NTR: subtypes of gender identity datum

### ISSUE THREAD

**Issue by cstoeckert** [ufbmi/OMRSE#60]
I am requesting 'female identity datum' and 'male identity datum' as subtypes of 'gender identity datum'. They are needed for the Ontology for Biobanking as requested by the NCI BBRB to cover information obtained by their GTEx Clinical Collection Case Report Form. The definition they have for female gender is:
"A person who belongs to the sex that normally produces ova. The term is used to indicate biological sex distinctions or cultural gender role distinctions or both."
Male gender is similarly defined (..normally produces sperm). 
To be more Aristotelian, I suggest for 'female identity datum'
A gender identity datum that is intended to be a truthful statement about a person's subjective sense of their gender as being female, a person who belongs to the sex that normally produces ova.

**Comment by aellenhicks** [comment]
If you are interested in capturing biological properties you may want to consider using biological sex instead of an identity datum. ICBO 2016 has a paper describing the difference.


One's subjective sense of gender does not necessarily entail a sense of having a particular biogical sex or a particular set of organs. For example, transwomen do not have a subjective sense of having a body that would normally producing ova. If you need something else that captures gender identity as distinct from biological sex, I'm happy to help figure out how to do that.


Amanda Hicks, PhD
Assistant Professor, Health Outcomes & Policy
College of Medicine
University of Florida
CTRB 3226
PO Box 100219
2004 Mowry Road
Gainesville, FL  32610
p: (352) 294-5932<tel:%28352%29%20294-4197>
f: (352) 273-8703<tel:%28352%29%20273-8703>
aehicks@ufl.edu<mailto:hoganwr@ufl.edu>
________________________________

**Comment by cstoeckert** [comment]
Hi Amanda,
We want both biological sex (quality) and gender identity item (ICE) in OBIB because they are different as you clearly present in your paper. I understand the definition I offered is not sufficient but felt compelled to include what was provided from the original term requesters. I would very much appreciate your help in figuring out how to define the ICE that results from a gender identification process when a person chooses the label 'female' (and when the person chooses 'male').
Thanks, Chris

**Comment by cstoeckert** [comment]
A suggested way to go that takes advantage of the gender identification process but does not attempt to define male or female is:
- female gender identity datum: a gender identity datum resulting from a gender identification process in which ‘female’ is selected based on the participant's subjective sense of gender.
- male gender identity datum: a gender identity datum resulting from a gender identification process in which ‘male’ is selected based on the participant's subjective sense of gender.

**Comment by aellenhicks** [comment]
These classes were created with the proposed definitions.
