### ISSUE TITLE
term request - language

### ISSUE THREAD

**Issue by hoganwr** [ufbmi/OMRSE#7]
For handling various EHR demographics and standards like CCD, we need a class 'language'.

Note that the Mental Functioning Ontology defines it as "a complex disposition inhering in a population by virtue of the fact that members thereof can communicate with each other through speech" (MF_0000022).  Its parent is BFO:disposition.

We take issue with it at least slightly because a person can invent a language of her own to record things and use those recordings later to remind herself of what happened in the past.  She can also give it sounds, write lyrics in her language, etc.

Dolce includes a class for it, but doesn't give it a textual definition.

**Comment by aellenhicks** [comment]
Languages that are referred to by ISO codes will be individuals.

**Comment by aellenhicks** [comment]
Email sent to Jenna Hastings June 16.

**Comment by hoganwr** [comment]
Also, we will need to figure out how to relate an ICE to "its language".  An interesting task, especially for ICEs that have text written in different languages.  

Some thoughts: 
1. To write or speak in English means to write or speak using English vocabulary and according to English rules of grammar.  This is one reason my suggestion for language as a directive ICE was only half in jest...  

2. The rules need not be written down.

3. There need not be a written form of a language (although not sure how that impacts this issue).

4.  You could say that the language vocabulary/grammar rules are specified input into ICE creation.  Then whichever instance of those things are at play (English, Spanish, etc.) is the language of the ICE.  

5. Those vocabulary/grammar rules are also needed to read/understand/interpret an ICE.

**Comment by jannahastings** [comment]
Hi Amanda, others, 

I am not attached to the definition of language used in the MF, but note that:

(1) this definition refers to _communication via speech_ specifically so it might better be named 'human spoken language' in order to defer some of the objections you have. A language which is only for private use or written use by one individual would be out of scope for this definition, deliberately. 

(2) I believe that languages such as English should be individuals, not classes.

(3) By email you raised the question of whether a language by MF's definition should be considered a case of generic rather than specific dependence because of e.g. dead languages being brought back to life. Here, I suspect this is not possible without the intervening existence of a written language or some other ICE (e.g. a recording); the spoken language which died might better be thought of as having been cloned into a new individual via this indirect route rather than continued to exist? But I don't have a big stake in the way that this edge case is resolved. 

Clearly, there are many complex aspects of this question which are not in any way covered by MF's existing, rather unambitious, definition -- I thought that this was an area Barry (perhaps together with Mathias?) was planning to do more work in, not sure what the outcome of those earlier discussions have been.

I'm happy to make any changes you'd like to see in the MF!

Best wishes, 
Janna

**Comment by aellenhicks** [comment]
Hi Jenna,

Can you clarify what a complex disposition is?

best,
Amanda

**Comment by aellenhicks** [comment]
Posted this issue to MF.  https://github.com/jannahastings/mental-functioning-ontology/issues/1

**Comment by dillerm** [comment]
With the addition of the OMRSE-language module, I believe that this issue has been resolved.
