### ISSUE TITLE
Create class for salary

### ISSUE THREAD

**Issue by aellenhicks** [ufbmi/OMRSE#77]
Proposed definition by @seljaseppala zhengj2007 in issue #62 

salary: no definition (parent: IAO_0000027 data item)

**Comment by aellenhicks** [comment]
We have a class in OMRSE 'income data' which is subclass of 'data item'. It has no definition yet. Do you see a distinction between income data and salary as a data item that we could capture?

**Comment by dillerm** [comment]
Is it fair to assume this is meant to be restricted to only monetary gains, as opposed to in non-monetary consumption opportunity (e.g., rations or goods acquired through bartering)?

**Comment by cstoeckert** [comment]
Our usage is restricted to monetary gains (i.e. salary/ wages).

**Comment by dillerm** [comment]
**proposed label** = monetary personal income data item 

**proposed definition** = A data item that is about the sum of earnings for some person(s) from wages, salary, or tips; interest generated by capital; receipt of rental payments; or profit from entrepreneurial activities.

**comment** = We use the phrase ‘some person’ in the definition because this class can be about an individual's or a household's earnings. Similarly, we use 'personal income' in the label because the term is typically restricted to individuals and households. This class is also restricted to being about monetary forms of income.

**Comment by cstoeckert** [comment]
This works for VEuPathDB/ClinEpi. 
Something to consider though is that enumerated lists aren't the best for definitions as it is usually not possible to be exhaustive and comprehensive. How about:
"A data item that is about the sum of earnings for some person(s) from various forms of payment or profits." Then use 'examples of usage' to list: wages, salary, or tips; interest generated by capital; dividends earned; lottery, game, or contest monetary winnings; alimony; royalties; trusts; pensions; receipt of rental payments; unemployment payments; social security payments; worker's compensation; social security payments; or profit from entrepreneurial activities.

**Comment by LightGrenadier** [comment]
We are good to move forward with the proposed change.
